export const TYPES ={
    CREATE_DATA:"CREATE_DATA",
    READ_ALL_DATA:"READ_ALL_DATA",
    UPDATE_DATA:"UPDATE_DATA",
    DELETE_DATA:"DELETE_DATA",
    READ_ALL_CATEGORY:"READ_ALL_CATEGORY",
    READ_ONE_CATEGORY:"READ_ONE_CATEGORY",
    REMOVE_CATEGORY:"REMOVE_CATEGORY",
    NO_DATA:"NO_DATA",
}