export const TYPES ={
    READ_ALL_DATA:"READ_ALL_DATA",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_ONE_FROM_CART:"REMOVE_ONE_FROM_CART",
    REMOVE_ALL_FROM_CART:"REMOVE_ALL_FROM_CART",
    READ_ALL_CATEGORY:"READ_ALL_CATEGORY",
    READ_ONE_CATEGORY:"READ_ONE_CATEGORY",
    REMOVE_CATEGORY:"REMOVE_CATEGORY",
    ADD_TO_PAY:"ADD_TO_PAY",
    NO_DATA:"NO_DATA",
    ADD_TO_QUANTITY:"ADD_TO_QUANTITY",
};
